#!/usr/bin/env ruby
require 'redcarpet'
require 'active_support/all'
require 'rainbow/refinement'
using Rainbow

require_relative 'src/templating/document'
require_relative 'src/templating/template_manager'

require_relative 'src/cli/command'
require_relative 'src/cli/build_command'
require_relative 'src/cli/open_command'
require_relative 'src/cli/new_command'

require_relative 'src/config'

command = ARGV[0]
commands_hash = COMMANDS.map { |x| [x.name, x] }.to_h
if commands_hash[command]
  commands_hash[command].run(ARGV[1..-1])
else
  puts [
    "    ****    ".magenta,
    "  ********  ".magenta,
    " ***".magenta + "\\".white + "****** ".magenta + " The HackSoc",
    " ***".magenta + "/\\".white + "\\/".magenta.bright + "*** ".magenta + " Email Toolchain",
    "  ****".magenta + "/".magenta.bright + "***  ".magenta + " By Aaron Christiansen".black.bright,
    "    ****    ".magenta,
    "",
    "Commands".underline,
  ] + COMMANDS.map(&:help_line)
end
