#!/usr/bin/env ruby
require 'redcarpet'
require 'active_support/all'
require 'rainbow/refinement'
using Rainbow

require_relative 'src/email_templating/document'
require_relative 'src/email_templating/template_manager'

require_relative 'src/cli/command'

require_relative 'src/cli/email/lint_command'
require_relative 'src/cli/email/build_command'
require_relative 'src/cli/email/open_command'
require_relative 'src/cli/email/new_command'

require_relative 'src/cli/talk_ad/json_command'

require_relative 'src/config'

category = ARGV[0]
command = ARGV[1]
commands_hash = COMMANDS.map { |x| [[x.category, x.name], x] }.to_h
if commands_hash[[category, command]]
  commands_hash[[category, command]].run(ARGV[2..-1])
else
  puts [
    "    ****    ".magenta,
    "  ********  ".magenta,
    " ***".magenta + "\\".white + "****** ".magenta + " The HackSoc",
    " ***".magenta + "/\\".white + "\\/".magenta.bright + "*** ".magenta + " LambdaTool",
    "  ****".magenta + "/".magenta.bright + "***  ".magenta + " By Aaron Christiansen".black.bright,
    "    ****    ".magenta,
    "",
    "Commands".underline,
  ] + COMMANDS.map(&:help_line)
end
